"""mission archive and task index

Revision ID: c2e876afbcae
Revises: 8a5b95fb297e
Create Date: 2026-05-30 12:03:20.948409
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c2e876afbcae'
down_revision = '8a5b95fb297e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_archive',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('final_status', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.BigInteger(), nullable=True),
    sa.Column('responder_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('task_total', sa.Integer(), nullable=False),
    sa.Column('task_completed', sa.Integer(), nullable=False),
    sa.Column('chat_message_count', sa.Integer(), nullable=False),
    sa.Column('location_sample_count', sa.Integer(), nullable=False),
    sa.Column('skills_used', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_archive_mission_id'), 'mission_archive', ['mission_id'], unique=True)
    op.create_index(op.f('ix_mission_archive_year'), 'mission_archive', ['year'], unique=False)
    op.create_index('ix_tasks_mission_status', 'tasks', ['mission_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_mission_status', table_name='tasks')
    op.drop_index(op.f('ix_mission_archive_year'), table_name='mission_archive')
    op.drop_index(op.f('ix_mission_archive_mission_id'), table_name='mission_archive')
    op.drop_table('mission_archive')
    # ### end Alembic commands ###
